version: "3.8"
services:
  fiber:
    container_name: fiber-fm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:7000
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fm

  postgres:
    image: postgres:16.0-alpine
    ports:
      - ${DATA_SOURCE_PORT}:${DATA_SOURCE_PORT_DOCKER}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fm
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8082:8080
    depends_on:
      - postgres

volumes:
  postgres:
